@startuml
title SmartHomeSystem Telemetry Microservice

top to bottom direction

!include ./C4_Component.puml

class TelemetryMicroserviceHandler {
  +PostTelemetryData
  +GetTelemetryHistoryData
  +GetTelemetryLatestData
}

class TelemetryMicroserviceService {
  +AddTelemetry
  +GetTelemetryLatest
  +GetTelemetryHistory
}

class TelemetryMicroserviceTelemetryRepo{
  +GetLatestTelemetry
  +GetHistoricalTelemetry
  +AddTelemetry
}

class TelemetryMicroserviceDeviceRepo{
  +CreateDevice
  +UpdateDevice
  +GetDeviceById
}

class TelemetryMicroserviceWorker {
  +void Process
}

class TelemetryMicroserviceTelemetryDatabusPublisher {
    + PublishTelemetry
}

TelemetryMicroserviceHandler ..> TelemetryMicroserviceService : uses
TelemetryMicroserviceService ..> TelemetryMicroserviceTelemetryRepo : uses (get/save telemetry)
TelemetryMicroserviceService ..> TelemetryMicroserviceDeviceRepo : uses (check device exists and in correct status)
TelemetryMicroserviceService ..> TelemetryMicroserviceTelemetryDatabusPublisher : uses (pubslish telemetry msg)

TelemetryMicroserviceWorker ..> TelemetryMicroserviceTelemetryRepo : uses (create/update device info and status)


@enduml