@startuml
title SmartHome Context Diagram

top to bottom direction

!include ./C4_Context.puml

Person(user, "User", "A user of the SmartHome system")
Person(admin, "Admin", "Administrator of the SmartHome system")

System(SmartHomeSystem, "SmartHome System", "System manages user's smart home")

System_Ext(usersHome, "UserSmartHomeSystem", "Sensors and controllers")

Rel(user, SmartHomeSystem, "Uses the system: control smart home using SaaS system")
Rel(admin, SmartHomeSystem, "using admin panel")
Rel(SmartHomeSystem, usersHome,"Get sensors data, run command for controllers")

@enduml