@startuml
title SmartHome Context Diagram

top to bottom direction

'!include ./C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "A user of the SmartHome system")
Person(admin, "Admin", "Administrator of the SmartHome system")

System(SmartHomeSystem, "SmartHome System", "System manages user's smart home")

System_Ext(usersHome, "UserSmartHomeSystem", "Sensors and heating controllers")

Rel(user, SmartHomeSystem, "Uses the system: set on/off of home heating system, set temp, get current temp")
Rel(admin, SmartHomeSystem, "Register/update Sensors and controllers in the user's home")
Rel(SmartHomeSystem, usersHome,"Get sensors data, run command on/off for heating controllers")

@enduml